name: smart_grader
description: "Smart-Grader - Educational Grading System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.3.2
  share_plus: ^10.1.0
  path_provider: ^2.1.5
  intl: ^0.19.0
  url_launcher: ^6.3.0
  pdf: ^3.11.1
  printing: ^5.13.2
  shared_preferences: ^2.3.2
  fl_chart: ^0.70.1
  qr_flutter: ^4.1.0
  collection: ^1.18.0
  mobile_scanner: ^5.2.3
  image_picker: ^1.1.2
  excel: ^4.0.5
  http: ^1.2.2
  csv: ^6.0.0
  file_picker: ^8.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#00C4B4"
    theme_color: "#00C4B4"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/icon/
